# Generated by Django 3.1.5 on 2021-01-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(verbose_name='対応日時')),
                ('meeting_purpose', models.IntegerField(choices=[('商談', '商談'), ('電話', '電話'), ('その他', 'その他')], verbose_name='対応内容')),
                ('meeting_rank', models.IntegerField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], verbose_name='検討ランク')),
                ('meeting_contents', models.TextField(max_length='5000', verbose_name='商談メモ')),
                ('meeting_next_action', models.TextField(max_length='5000', verbose_name='次のアクション')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
