# Generated by Django 3.1.5 on 2021-01-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0002_auto_20210115_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes',
            name='meeting_purpose',
            field=models.IntegerField(choices=[('商談', '商談'), ('電話', '電話'), ('その他', 'その他')], verbose_name='対応内容'),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='meeting_rank',
            field=models.IntegerField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], verbose_name='検討ランク'),
        ),
    ]
