# Generated by Django 3.1.5 on 2021-01-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0003_auto_20210115_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes',
            name='meeting_purpose',
            field=models.IntegerField(choices=[(1, '商談'), (2, '電話'), (3, 'その他')], verbose_name='対応内容'),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='meeting_rank',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C')], verbose_name='検討ランク'),
        ),
    ]
