# Generated by Django 3.1.5 on 2021-01-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0004_auto_20210115_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes',
            name='meeting_purpose',
            field=models.CharField(choices=[('商談', '商談'), ('電話', '電話'), ('その他', 'その他')], max_length=10, verbose_name='対応内容'),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='meeting_rank',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='検討ランク'),
        ),
    ]
